### ISSUE TITLE
Building a 58mb js ? 

### ISSUE THREAD

**Issue by mdisec** [schiesser-it/splunk-react-boilerplate#4]
Hey mate,

Amazing boileplate project. Tyvm for the effort. 

My question is: when I run `yarn run clean && NODE_ENV=production webpack --bail` it generates 58mb compressed js file. I believe it ships and compress all of the dependencies (including the one current ui already use) because of we are building the whole UI from via app ?

Other apps I've analysed uses sub 1mb single js files (they also uses react too)

**Comment by vtsvetkov-splunk** [comment]
The big contributor to the size are source maps.
```js
devtool: 'eval-source-map' // can be disabled with false
```
This parameter injects sourcemaps in JS file that inflates startPage.js from 10.4 mb to 58.7 mb. So, setting it to `false` (in production mode, for example) would solve the problem

**Comment by mdisec** [comment]
thanks for the info mate <3
